services:
  gz:
    image: gazebo:v9
    user: "user"
    volumes:
      - .:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - /dev/dri:/dev/dri            # keep for OpenGL context
    hostname: gz9
    extra_hosts:
      - "gz9:127.0.0.1"
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      
